  # book_Ticket = tk.Button(self.left_frame, text="Book Ticket", bg="blue", fg="white", command=self.book_ticket)
        # book_Ticket.pack(fill=tk.X, pady=5)
        # delete_Ticket = tk.Button(self.left_frame, text="Delete Ticket", bg="red", fg="white", command=self.delete_ticket)
        # delete_Ticket.pack(fill=tk.X, pady=5)
        # search_Ticket = tk.Button(self.left_frame, text="Search Ticket", bg="green", fg="white", command=self.search_ticket)
        # search_Ticket.pack(fill=tk.X, pady=5)
        # show_all_Tickets = tk.Button(self.left_frame, text="Show All Tickets", bg="purple", fg="white", command=self.show_all_tickets)
        # show_all_Tickets.pack(fill=tk.X, pady=5)
        # total_Fare = tk.Button(self.left_frame, text="Total Fare", bg="orange", fg="black", command=self.show_total_fare)
        # total_Fare.pack(fill=tk.X, pady=5)